print("--------- Try It Yourself! ---------")
print('------------------------------------')
animes = ['dragon ball super', 'naruto', 'bleach', 'one piece']
print('List of Favorite Anime: ' + str(animes))
print(animes[0].title())
print(animes[1].title())
print(animes[2].title())
print(animes[3].title())
print('------------------------------------')
print('\tChanging Entry')
print('------------------------------------')
animes[3] = 'black clover'
print('List of Favorite Anime: ' + str(animes))
print('------------------------------------')
print('\tAppend Entry')
print('------------------------------------')
animes.append('one piece')
print('List of Favorite Anime: ' + str(animes))
print('------------------------------------')
print('\tInsert Entry')
print('------------------------------------')
animes.insert(2,"full metal alchemist: brotherhood")
print('List of Favorite Anime: ' + str(animes))
print('------------------------------------')
print('\t"Del" Entry')
print('------------------------------------')
del animes[5]
print("The One Piece... The One Piece is Real!!!!")
print('List of Favorite Anime: ' + str(animes))
print('------------------------------------')
print('\tPop() Method w/ Message')
print('------------------------------------')
popped_anime = animes.pop()
print('I used to watch ' + popped_anime.title() + " but then, King Julius died...")
print('List of Favorite Anime: ' + str(animes))
print('------------------------------------')
print('\tPositioned Pop() Method w/ Message')
print('------------------------------------')
popped_anime = animes.pop(0)
print('I have not watched ' + popped_anime.title() + " in quite some time.")
print('List of Favorite Anime: ' + str(animes))
print('------------------------------------')
print('\tRemoval w/ Message')
print('------------------------------------')
completed = 'full metal alchemist: brotherhood'
animes.remove(completed)
print("I have seen all of " + completed.title() + '. It was  a greate experience!')
print('List of Favorite Anime: ' + str(animes))
animes = ['dragon ball super', 'naruto', 'full metal alchemist: brotherhood', 'bleach', 'black clover', 'one piece']
print('------------------------------------')
print('Original Order: ' + str(animes))
print("\tTemp Sorted: " + str(sorted(animes)))
print('Original Order: ' + str(animes))
print('\tTemp Reverse Sorted: ' + str(sorted(animes, reverse=True)))
print('Original Order: ' + str(animes))
animes.reverse()
print("\tReverse Order: " + str(animes))
animes.reverse()
print("\tReturned from Reverse Order: " + str(animes))
print('Original Order: ' + str(animes))
animes.sort()
print('\tPerma Sort: ' + str(animes))
animes.sort(reverse=True)
print('\tReverse Perma Sort: ' + str(animes))
print('Number of favorite anime: ' + str(len(animes)))
