print("--------- Try It Yourself! ---------")
visiting_countries = ['japan','spain','mexico','russia','england']
print("List of countries I wish to visit: " + str(visiting_countries))
print('Alphabetical: ' + str(sorted(visiting_countries)))
print('------------------------------------')
print(visiting_countries)
print('------------------------------------')
print('Reverse Alphabetical: ' + str(sorted(visiting_countries,reverse=True)))
print(visiting_countries)
print('------------------------------------')
visiting_countries.reverse()
print('Reversed: ' + str(visiting_countries))
print('------------------------------------')
visiting_countries.reverse()
print('Returned to Original: ' + str(visiting_countries))
print('------------------------------------')
visiting_countries.sort()
print('Perma Sorted: ' + str(visiting_countries))
print('------------------------------------')
visiting_countries.sort(reverse=True)
print('Reverse Perma Sorted: '+ str(visiting_countries))