print("--------- Try It Yourself! ---------")
numbers = list(range(1,1000001))
print('Minimum: ' + str(min(numbers)))
print('Maximum: ' + str(max(numbers)))
print('Summation: ' + str(sum(numbers)))
print('------------------------------------')
print(min(numbers))
print(max(numbers))
print(sum(numbers))